// <auto-generated />
namespace Whiteboard.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    
    public sealed partial class InitialCreate : IMigrationMetadata
    {
        string IMigrationMetadata.Id
        {
            get { return "201208031348236_InitialCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return "H4sIAAAAAAAEAM1WzVLbMBC+d6bv4PGpPdQKnKDjwEBCGKYN6WCgZ8VeJ5pKspFkJn62HvpIfYWu4t/YCYSfQy+ZWNrd79Put1r9/f3HP10J7jyC0iyRQ/fAG7gOyDCJmFwM3czEX47c05OPH/yLSKyc+8ru0Nqhp9RDd2lM+pUQHS5BUO0JFqpEJ7HxwkQQGiXkcDA4IgcDAhjCxViO499k0jAB6w/8HCUyhNRklE+TCLgu13EnWEd1rqkAndIQhu7PJTMwT6iKvMLYdc44o0gkAB6/kNXg2LJyazxEvEBmJr/NU1ijDt1zi9U2QaNvkG8s4NIPlaSgTH4Dcel4FbkO2fQjXcfareVjsYfuZcbw/3XGOZ1z/I4p19AL2HG3v1WAwCgsoutM2Aqi7yAXZllHmdJVtYJ/XedOMqw5OhmVwYtRRwqogeg8v9Og3hW++G6j+6QpUL9sKCRDmQRVMmvEYndgZTp1LLwCMO1ao6IajEJWXiGCrUxqzEa1pJBtJW+yQ9/+lKYpJqml93LFCQqxj74EL1e0KGKQUG8Rds22RjKJogvo7CI0Mp0wpc2YGjqntmyjSPTM9s5whbeR6G4TNXmvzO3/bi3Lxve2dGY7iRM8lwBp1keEmsjWji49g5Byqrb05CjhmZC7+vop76Il2/7Fyv4ROu3VDtXZ6sf0SScZ3YyTXso7N1a3gE91QNekRq87oaN4v1Tf89d+T46Fietgsh5ZZKUY5NqA8KyBFzzwEWd43sZgSiWLQZvb5BfYEYbd8vrRcUwGh3Z0EK0j/l/Oj0yyhwzw4MgnZlYdb5gl8pGqcEnVJ0FXn99nPuwM+dY7v39x7XHn777yC50N3WieIPWCYjUmXjkO+qL3SftF5I9Bs0UTwr6PJIQGn15N0MrmSsZJlW88VJtRZdIpxxQMjTA3ZwqVQUOD2yFovZ7W95RnaHIh5hBdyVlm0sycaQ1izvP2eX3yNP565m1y9mep/dLvcQSkyfAIMJPnGeNRzXvSl+OuEFYml4Dr1LLC1wqGW+R1pOtE7hmoTN8YUpC2225BpByD6ZkM6CPs5vZ8Djcz5o8ZXSgq2hksVkomAUXkFgQCtD0aPPugJ/ZFf/IP/TBR4QMMAAA="; }
        }
    }
}
